# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_new_class_window(object):
    def setupUi(self, Add_new_class_window):
        Add_new_class_window.setObjectName("Add_new_class_window")
        Add_new_class_window.resize(481, 175)
        font = QtGui.QFont()
        font.setPointSize(9)
        Add_new_class_window.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Add_new_class_window)
        self.pushButton.setGeometry(QtCore.QRect(170, 130, 141, 23))
        self.pushButton.setObjectName("pushButton")
        self.Class_name_line_edit = QtWidgets.QLineEdit(Add_new_class_window)
        self.Class_name_line_edit.setGeometry(QtCore.QRect(70, 60, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Class_name_line_edit.setFont(font)
        self.Class_name_line_edit.setAutoFillBackground(False)
        self.Class_name_line_edit.setObjectName("Class_name_line_edit")

        self.retranslateUi(Add_new_class_window)
        QtCore.QMetaObject.connectSlotsByName(Add_new_class_window)

    def retranslateUi(self, Add_new_class_window):
        _translate = QtCore.QCoreApplication.translate
        Add_new_class_window.setWindowTitle(_translate("Add_new_class_window", "New Class"))
        self.pushButton.setText(_translate("Add_new_class_window", "Zapisz"))
        self.Class_name_line_edit.setText(_translate("Add_new_class_window", "asd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_new_class_window = QtWidgets.QWidget()
    ui = Ui_Add_new_class_window()
    ui.setupUi(Add_new_class_window)
    Add_new_class_window.show()
    sys.exit(app.exec_())
