# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign-statistics-annotation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotation_statistics_window(object):
    def setupUi(self, annotation_statistics_window):
        annotation_statistics_window.setObjectName("annotation_statistics_window")
        annotation_statistics_window.setWindowModality(QtCore.Qt.WindowModal)
        annotation_statistics_window.resize(622, 479)
        font = QtGui.QFont()
        font.setPointSize(9)
        annotation_statistics_window.setFont(font)
        self.annotation_listWidget = QtWidgets.QListWidget(annotation_statistics_window)
        self.annotation_listWidget.setGeometry(QtCore.QRect(20, 60, 561, 381))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.annotation_listWidget.setFont(font)
        self.annotation_listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.annotation_listWidget.setObjectName("annotation_listWidget")
        self.title_label = QtWidgets.QLabel(annotation_statistics_window)
        self.title_label.setGeometry(QtCore.QRect(30, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")

        self.retranslateUi(annotation_statistics_window)
        QtCore.QMetaObject.connectSlotsByName(annotation_statistics_window)

    def retranslateUi(self, annotation_statistics_window):
        _translate = QtCore.QCoreApplication.translate
        annotation_statistics_window.setWindowTitle(_translate("annotation_statistics_window", "Adnotacje"))
        self.title_label.setText(_translate("annotation_statistics_window", "Adnotacje"))
